# available tags
#   #ROOT#            - root folder for all files
#   #TODAY#           - todays date
#   #PATCH_NAME#      - name for prepared patch file (run/install script)
#   #ENV_NAME#        - environemnt name used for logs
#   #APP_ID#          - APEX app id, translated during processing
#   #SCHEMA_NAME#     - schema name, translated during processing
#

# basic folders
git_root        : '#ROOT#/'
git_target      : '#ROOT#/database/'        # exported database objects
patch_root      : '#ROOT#/patches/'         # extra objects included when -patch(ing)
patch_done      : '#ROOT#/patches_done/'    # output files from patching

# log files and output files
patch_today     : '#ROOT#/patches_done/#ENV_NAME#/#TODAY#.sql'          # when no patch name is provided
patch_zip       : '#ROOT#/patches_done/#ENV_NAME#/#TODAY#.zip'
patch_named     : '#ROOT#/patches_done/#ENV_NAME#/#PATCH_NAME#.sql'     # when patch name is provided
patch_log       : '#ROOT#/patches_done/#ENV_NAME#/patch.log'
rollout_log     : '#ROOT#/patches_done/#ENV_NAME#/rollout.log'
locked_log      : '#ROOT#/patches_done/locked.log'
patch_manually  : '#ROOT#/patches/30_table+data_changes/#TODAY#.sql'    # dedicated for table changes

# APEX related
apex_dir        : '#ROOT#/database/apex/'
apex_temp_dir   : '#ROOT#/database/apex/temp/'
apex_ws_files   : '#ROOT#/database/apex/workspace_files/'
apex_app_files  : '#ROOT#/database/apex/f#APP_ID#_files/'
apex_tmp        : apex.#APP_ID#.tmp

# APEX exports
apex_embedded           : True        # export embedded code
apex_splited            : True        # export splitted application
apex_full               : True        # traditional full export
apex_files              : True        # export workspace files
apex_show_changes       : True        # show app changes made in -recent days
apex_clean_timestamps   : True        # convert timestamps to a single value
apex_clean_authors      : True        # convert authors to a single value
apex_add_name_comments  : True        # add (some) component names as comments
apex_switch_auth        : True        # switch authentication scheme to default
apex_set_version        : '#TODAY#'   # overwrite application version with today date

# target folders by object types
folders:
  APEX                : ['#ROOT#/database/apex/',         .sql]
  DATA                : ['#ROOT#/database/data/',         .csv]
  FUNCTION            : ['#ROOT#/database/functions/',    .sql]
  GRANT               : ['#ROOT#/database/grants/',       .sql]
  INDEX               : ['#ROOT#/database/indexes/',      .sql]
  JOB                 : ['#ROOT#/database/jobs/',         .sql]
  MATERIALIZED VIEW   : ['#ROOT#/database/mviews/',       .sql]
  MVIEW LOG           : ['#ROOT#/database/mview_logs/',   .sql]
  PACKAGE             : ['#ROOT#/database/packages/',     .spec.sql, .pks]   # alternative ext.
  PACKAGE BODY        : ['#ROOT#/database/packages/',     .sql,      .pkb]
  PROCEDURE           : ['#ROOT#/database/procedures/',   .sql]
  SEQUENCE            : ['#ROOT#/database/sequences/',    .sql]
  SYNONYM             : ['#ROOT#/database/synonyms/',     .sql]
  TABLE               : ['#ROOT#/database/tables/',       .sql]
  TRIGGER             : ['#ROOT#/database/triggers/',     .sql]
  VIEW                : ['#ROOT#/database/views/',        .sql]

# grants, resp. privileges
grants_recd         : '/received/#SCHEMA_NAME#.sql'       # received grants, under GRANT folder
grants_privs        : '/#SCHEMA_NAME#_schema.sql'         # grants used to create schema
grants_directories  : '/#SCHEMA_NAME#_directories.sql'

# export objects by type in this order
objects_sorted:
  - SYNONYM
  - SEQUENCE
  - TABLE
  - VIEW
  - FUNCTION
  - PROCEDURE
  - PACKAGE
  - PACKAGE BODY
  - TRIGGER
  - INDEX
  - MVIEW LOG
  - MATERIALIZED VIEW
  - JOB

# option to remove objects before create
drop_objects:
  - MATERIALIZED VIEW
drop_objects_mview_log:
  - MVIEW LOG

# map objects to patch folders
patch_map:
  init: []
  sequences:
    - SEQUENCE
  tables:
    - TABLE
  synonyms:
    - SYNONYM
  objects:
    - VIEW
    - PROCEDURE
    - FUNCTION
    - PACKAGE
    - PACKAGE BODY
  triggers:
    - TRIGGER
  mviews:
    - MVIEW LOG
    - MATERIALIZED VIEW
  indexes:
    - INDEX
  data:
    - DATA
  grants:
    - GRANT
  jobs:
    - JOB

# patch folders, sorted
patch_folders:
  init      : '#ROOT#/patches/10_init/'
  sequences : '#ROOT#/patches/20_new_sequences/'
  tables    : '#ROOT#/patches/25_new_tables/'
  changes   : '#ROOT#/patches/30_table+data_changes/'
  synonyms  : '#ROOT#/patches/35_synonyms/'
  objects   : '#ROOT#/patches/40_repeatable_objects/'
  triggers  : '#ROOT#/patches/45_triggers/'
  mviews    : '#ROOT#/patches/50_mviews/'
  indexes   : '#ROOT#/patches/55_indexes/'
  data      : '#ROOT#/patches/60_data/'
  grants    : '#ROOT#/patches/70_grants/'
  jobs      : '#ROOT#/patches/80_jobs/'
  finally   : '#ROOT#/patches/90_finally/'

# track changes in some folders + track all files starting with YYYY-MM-DD
# other patch folders will be treated as repeatable
patch_tracked:
  - tables
  - changes
  - data

# @@ = relative to script from which it is called from
patch_line  : '@@"../../{}"'

# for CSV files dont export audit columns
ignore_columns:
  - updated_at
  - updated_by
  - created_at
  - created_by

# flags in filenames to adjust which operations do in MERGE
merge_insert: .I.   # it is required to start with dot
merge_update: .U.
merge_delete: .D.

# provide option to skip flags
merge_auto_insert: True
merge_auto_update: False
merge_auto_delete: True

# filter table data before export to CSV file
csv_export_filters:
  NAVIGATION : 'app_id > 0'

# auto verbose on
auto_verbose : True

# auto add and lock new object with the prefix
auto_lock_add_prefix : ''

# auto refresh and auto add CSV files
auto_csv_refresh  : True
auto_csv_add      : ['LOV_%']

